version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      dev-dependencies:
        patterns: ['*']
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: monthly
    groups:
      website-dependencies:
        patterns: ['*']
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
